# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-08 15:41
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyQuotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('collected_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
