version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - API_BASE_URL=http://localhost
      - API_BASE_PORT=8000
      - HGBRASIL_API_URL=https://api.hgbrasil.com/finance/quotations?format=json&key=
      - HGBRASIL_API_KEY=ffbc7ead